### ISSUE TITLE
Remove/hide account info in upper right

### ISSUE THREAD

**Issue by mvines** [solana-labs/blockexplorer#10]
Until we have functional stuff in the account menu, let's hide it:
![image](https://user-images.githubusercontent.com/1281082/52965763-72f14b00-335a-11e9-8b8e-4ba94925f6e0.png)

**Comment by sunnygleason** [comment]
ok, will hide!

**Comment by sunnygleason** [comment]
in #15

**Comment by sunnygleason** [comment]
(fix merged to master)
