### ISSUE TITLE
Add ability to deep link to a transaction signature

### ISSUE THREAD

**Issue by mvines** [solana-labs/blockexplorer#11]
From example-tictactoe, I'd like to be able to click on a transaction signature and deep link the user into the blockexplorer UI to show the transaction details.

Perhaps something like `http://edge.testnet.solana.com/transaction/ur36jCttDd3KtzEYHDdf8MdmdX9EMJjafVe8MYpssj8mSHVrukJ6egNfbp7oXM8eSAbzhYECFYXxT3qyXTvThUh`

**Comment by sunnygleason** [comment]
Do we have system-side abbreviations? I've been using ```txn```, ```blk```, and ```ent``` for transaction, block and entry respectively. There may also be a URL path delimiter for React Routing -- I'll update this issue with any impact for your review & we can change it if necessary.

**Comment by sunnygleason** [comment]
in PR #15

**Comment by mvines** [comment]
I hate abbreviations in general.  Just type/autocomplete the full thing and don't leave future readers confused

**Comment by sunnygleason** [comment]
@mvines apologies I didn't see this -- just replied on-channel to hopefully discuss with product folks, the design docs I have have abbreviations, am ready to go with your approach, just want to make sure we're all on the same page. If we need to change after discussion, will definitely open a new issue to track...
