### ISSUE TITLE
Add ability to filter transactions by program id (ideally with a deep link entrypoint)

### ISSUE THREAD

**Issue by mvines** [solana-labs/blockexplorer#12]
* [x] From example-tictactoe, I'd like to be able to click on a program id and arrive at a blockexplorer UI that lists all recent transactions that included this program id.
* [x] Directly from the blockexplorer UI, the user should be able to enter a program ID manually and arrive at the same result

**Comment by sunnygleason** [comment]
@mvines nice, I like this one. will follow up on #blockexplorer with a couple questions...

**Comment by sunnygleason** [comment]
implemented in #28
