### ISSUE TITLE
Remove Entry and Tick entities from UI

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/blockexplorer#17]
Both Entry and Tick are a solana-specific concepts that won't be terribly meaningful to users. Let's abstract them from the UI. Steps might look something like this:
- [x] Remove latest-entries panel from homepage
- [x] Remove Tick Height counter
- [x] Remove entry and tick references from block- and transaction-details modals
- [x] Implement a "pending" status for transactions to display in Transaction Details until the block id is available, or only update UI once a block has completed.

**Comment by sunnygleason** [comment]
implemented by #28
