### ISSUE TITLE
Various Styling Thoughts

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/blockexplorer#19]
A bunch of random small design/styling things:

- [x] There's something a bit funky with the page width; no matter how wide I make my browser window, I always have a horizontal scroll bar
- [x] Black hyperlinks not ideal, especially in the case of block and tx ids. Maybe solana teal?
- [x] Graph points, lines, and area-under-the-curve are difficult to see with current theme. Maybe variations of teal, like currently used in the Transactions graph here: https://metrics.solana.com:3000/d/testnet-beta/testnet-monitor-beta
- [x] Graph units a little hard to read on some monitors. Maybe slightly lighter gray?
- [x] Why is the right-most graph interval 5min and the rest are 3min?
- [x] Panel titles need padding from the edge of the panel. Match table content?
- [x] The tooltip-like links to solana terminology look a little odd. Perhaps giving them a little padding from the string and superscript? Or perhaps using a tooltip glyphicon (often a question mark in a circle) would be more instinctive.
- [x] The width of search icon ("BxAppBar-searchIcon-8") seems a little wide. Will need to drop the left padding on the input element as well.
- [x] In block modal, list of entries (soon to be transactions), display only one id per line (commas are hard to pick out)
- [x] Pretty-print raw data in block and transaction modals?

**Comment by sunnygleason** [comment]
@CriesofCarrots this is ready to check out, apologies for the delay, I got stuck in the middle of rebasing!
