### ISSUE TITLE
Zoom in Transaction Graph?

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/blockexplorer#20]
I'm not certain what makes the most compelling view of TPS over time.
One thought is to zoom in to the last 5-10min, and show average TPS at a resolution of 3sec or 5sec. Graph could update somewhat slower, if that seems like too much movement.

Whatever the resolution, update units to average transactions per second.

**Comment by sunnygleason** [comment]
legend updated in #28; I'm guessing we'll get a real spec for the graph in an upcoming product meeting, so not going too deep right now
