### ISSUE TITLE
No indication of truncation in search bar

### ISSUE THREAD

**Issue by mvines** [solana-labs/blockexplorer#286]
![image](https://user-images.githubusercontent.com/1281082/63725423-227a0f00-c80f-11e9-85c9-2146e7a66d1a.png)
 
What's a "keyb"?   There should be an "..." or something so I have a visual hint that this is really "keybase" (if I make my browser window larger"

**Comment by sunnygleason** [comment]
I believe fix is visible at : https://edge.explorer.solana.com/
