### ISSUE TITLE
Inconsistent alignment of the '?'

### ISSUE THREAD

**Issue by mvines** [solana-labs/blockexplorer#290]
![image](https://user-images.githubusercontent.com/1281082/63725783-396d3100-c810-11e9-878b-bd9367f87cb4.png)
vs
![image](https://user-images.githubusercontent.com/1281082/63725794-4558f300-c810-11e9-9268-b10661d8b3c0.png)

**Comment by sunnygleason** [comment]
I believe fix is visible at : https://edge.explorer.solana.com/
