### ISSUE TITLE
Inconsistent map labels between network overview/validators tab

### ISSUE THREAD

**Issue by mvines** [solana-labs/blockexplorer#296]
Both these maps show the same thing but are named differently:
![image](https://user-images.githubusercontent.com/1281082/63726153-48081800-c811-11e9-932a-7f942f3cde2d.png)
vs
![image](https://user-images.githubusercontent.com/1281082/63726168-4fc7bc80-c811-11e9-8e75-036db30e88e8.png)

**Comment by sunnygleason** [comment]
I believe fix is visible at : https://edge.explorer.solana.com/
