### ISSUE TITLE
Search by keybase name doesn't appear to work

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/blockexplorer#302]
STR:
I attempted to search for one of the solana validators by name in the search box, and got no results. In case there is something idiosyncratic about those validators, I also spun up my own validator and added solana-validator-info linking to keybase name "tyera", but got no search results on that either, even though the validator showed up in the list

![image](https://user-images.githubusercontent.com/3030561/63809815-88829700-c8e0-11e9-97aa-66d61534c739.png)

**Comment by sunnygleason** [comment]
I think this is available at https://edge.explorer.solana.com/, search
by partial string match on node name & pubkey appears to work.

If possible, it would be great to fire up the 'tyera' keybase account just
to double check...

**Comment by CriesofCarrots** [comment]
> If possible, it would be great to fire up the 'tyera' keybase account just
> to double check...

@sunnygleason , I'll give it a go sometime soon.

One thing that seems weird to me about the current implementation is that if I start typing a node Name, the suggested results don't include that Name or information about matching; just the validator pubkey. Perhaps we need design input on this, but I think the matched results need to show just the Name, or both Name and pubkey

**Comment by CriesofCarrots** [comment]
This only works for the 'tyera' node -- by name or by pubkey -- after my stake has warmed up. That doesn't seem right.
I'll open a new issue.
