### ISSUE TITLE
Data label cleanup

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/blockexplorer#303]
1. Inconsistency between pages:
   Validators page: Total Circulating SOL
   TdS page: Total SOL In Circulation

2. Some unnecessary words/characters:
   Remove the word "Total" from Staked and Circulating SOL
   Remove "#" and "# of" from Active/Inactive Validators

**Comment by sunnygleason** [comment]
I believe fix is visible at : https://edge.explorer.solana.com/
