### ISSUE TITLE
No network change data-loading animation on Validators or TdS

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/blockexplorer#306]
On Validators or TdS pages when change Network select, there is no indication that data is loading. Implement something like on the Network Overview page?

**Comment by sunnygleason** [comment]
I believe fix is visible at : https://edge.explorer.solana.com/

**Comment by CriesofCarrots** [comment]
However, this effect is not applied to the validators table, which means the old testnet validator names hang around for a bit. I will file a new issue.
