### ISSUE TITLE
TdS position depends on validator name length

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/blockexplorer#317]
The length of the TdS bike "path" depends on the length of the validator name up to the truncation length. (Obvious during the dry run, as all validators stay at the beginning)

![image](https://user-images.githubusercontent.com/3030561/63882711-cb4f7800-c98f-11e9-9f8d-255bd2c024b9.png)

(Haha, I'm winning! You should have picked a longer name, @mvines !)

**Comment by sunnygleason** [comment]
I believe fix is visible at : https://edge.explorer.solana.com/
