### ISSUE TITLE
Clean up port handling

### ISSUE THREAD

**Issue by mvines** [solana-labs/blockexplorer#43]
Right now we run on port [80](https://github.com/solana-labs/blockexplorer/blob/master/package.json#L68), and `sudo` [our way there](https://github.com/solana-labs/blockexplorer/blob/38b0ad76e5cfed95a8c8a981a30a4e5d52eb0e20/bin/blockexplorer.sh#L48-L51) on Linux (and wannabe Linux environments like WSL).

There's a number of problems with this:
* Running `npm` as root is simply a terrible idea
* Assuming port 80 by default is not super
* We aren't really compatible with environments like Heroku that want to give you a port.

An alternative is:
* Use the `PORT` environment variable to select the port to run on (defaulting to an unprivileged port like 8000)
* Update the `net/` scripts in the main solana repo to use `iptables` to forward port 80 to port 8000 so the blockexplorer doesn't need sudo and remains on port 80

**Comment by sunnygleason** [comment]
On my local & cloud linux boxes, I've been running the services
via a unix domain socket with haproxy doing the privileged stuff.
If that's interesting, I can contribute the setup...

**Comment by mvines** [comment]
I'm not attached to iptables, or any port redirection solution, so haproxy could work.  In our testnet setup, we start from a fresh Ubuntu 18.04 instance and install the things we need on it each time so my only preference is towards a solution that is quick and easy to install from a bash script

**Comment by mvines** [comment]
done
