### ISSUE TITLE
Use local time in the UI

### ISSUE THREAD

**Issue by mvines** [solana-labs/blockexplorer#8]
All the time information displayed appears to be in UTC, some examples below.  Let's use a library like https://momentjs.com/ to render local time.   Also for "last updated", we could use [Time from now](https://momentjs.com/docs/#/displaying/fromnow/).

![image](https://user-images.githubusercontent.com/1281082/52965449-ada6b380-3359-11e9-8ed0-5ad1d4e991b1.png)
![image](https://user-images.githubusercontent.com/1281082/52965464-b9927580-3359-11e9-875c-a5bb40201444.png)

**Comment by sunnygleason** [comment]
@mvines ok, plan will be to use browser local setting for date rendering via momentjs.

Will follow up with questions re: entry/block on #blockexplorer ...

**Comment by sunnygleason** [comment]
in PR #15

**Comment by sunnygleason** [comment]
(fix merged to master)
