### ISSUE TITLE
Remove/hide "This node"

### ISSUE THREAD

**Issue by mvines** [solana-labs/blockexplorer#9]
The current node that the blockexplorer is connected to is not really that interesting, and certainly not important enough to be in the prominent upper left of the UI.  Let's just remove it fror now: ![image](https://user-images.githubusercontent.com/1281082/52965637-23128400-335a-11e9-87f9-46e25cf7f00c.png)

**Comment by sunnygleason** [comment]
@mvines how about replacing it with ```current leader```?

At some point (esp in the context of forks), we'll also probably
need to pipe the cluster membership into blockexplorer. Would
that data be easy to get from the RPC API?

**Comment by mvines** [comment]
Current leader sounds great.    Getting the current leader would be best done via entry stream, since the leader should be rotating every block.

Cluster membership - yes probably through a new RPC API.  Although we then need to think about which node to ask about cluster membership as the cluster view of the api node that's servicing the blockexplorer may be different from what the current slot leader sees.  (probably best to continue this discussion in a dedicated issue)

**Comment by sunnygleason** [comment]
in PR #15

**Comment by sunnygleason** [comment]
(fix merged to master)
